spring:
  application.name: jandy
  freemarker:
    requestContextAttribute: rc
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    default-encoding: UTF-8
    properties:
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com
  redis:
    type: embedded
    port: ${random.int[10024,65536]}
security:
  basic.enabled: false
  oauth2:
    client:
      clientId: 5b6118bdbd4066c1ea7a
      clientSecret: 33e25aa49db0a3113ab222473b8e5483e5ec637d
      scope: email, public_repo, user
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.github.com/user
      preferTokenInfo: false
server.port: 3000
jandy:
  zk:
    type: embedded
multipart:
  enabled: true
  max-file-size: 512MB
  max-request-size: 1024MB
logging.level:
  io.jandy: TRACE
#  org.hibernate.SQL: debug
#  org.hibernate.type: trace
